[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--no-fund --no-audit"

[dev]
command = "npm run dev"
framework = "vite"
targetPort = 5173
