[build]
command = "npm install && npm run build"
publish = "dist"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--no-fund --no-audit"

[dev]
command = "npm run dev"
framework = "vite"
targetPort = 5173